name: Delivery

on:
  workflow_dispatch: {}
  schedule:
  - cron: "0 0 * * 0"
  push:
    branches:
    - main

concurrency:
  group: delivery-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
        - path: "doraemon"
          repository: "sre/doraemon"
        - path: "slacktee"
          repository: "sre/slacktee"

    steps:
    - name: Configure AWS Credentials
      id: configure-aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ECR }}
        mask-aws-account-id: false
        role-skip-session-tagging: true
        aws-region: ap-northeast-2

    - name: Set up QEMU
      id: setup-qemu
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: setup-docker-buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      id: login-docker-hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare Docker Metadata
      id: prepare-docker-metadata
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.APP_CONTAINER_REPOSITORY }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=ref,event=pr
          type=sha,prefix=,suffix=,format=short
          type=match,pattern=(v.*),group=1,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

    - name: Build Container Image
      id: build
      uses: docker/build-push-action@v4
      with:
        context: "{{defaultContext}}:${{ matrix.path }}"
        platforms: linux/amd64, linux/arm64
        # tags: |
        #   tedilabs/doraemon:latest
        #   ghcr.io/tedilabs/doraemon:latest

    - name: Push Container Image
      id: push
      uses: docker/build-push-action@v4
      with:
        context: "{{defaultContext}}:doraemon"
        platforms: linux/amd64, linux/arm64
        push: true
        tags: |
          tedilabs/${{ matrix.path }}:latest
          ghcr.io/tedilabs/${{ matrix.path }}:latest
